# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-8"
  config.vm.box_check_update = true

  # Create Jenkins Server
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "192.168.2.11"
    jenkins.vm.provider "virtualbox" do |v|
        v.name = "jenkins"
        v.memory = 1024
        v.cpus = 4
        v.linked_clone = true
        v.gui = false
    end
    jenkins.vm.provision "ansible_local" do |ansible|
        ansible.verbose = "vv"
        ansible.playbook = "playbook.yml"
    end
  end
end
