# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_check_update = true

  # Create Jenkins Server
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "192.168.1.2"
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080
    jenkins.vm.network "forwarded_port", guest: 9090, host: 9090
    jenkins.vm.network "forwarded_port", guest: 3306, host: 3306
    jenkins.vm.network "forwarded_port", guest: 22, host: 1234, id: "ssh"
    jenkins.vm.provider "virtualbox" do |v|
        v.name = "jenkins"
        v.memory = 4096
        v.cpus = 4
        v.linked_clone = true
        v.gui = false
    end
    jenkins.vm.provision "ansible_local" do |ansible|
        ansible.verbose = "vv"
        ansible.playbook = "playbook.yml"
    end
    jenkins.vm.provision :docker,
        images: ["ubuntu:14.04"]
  end
end
